### ISSUE TITLE
Fix seeds to work with agricraft cropsticks

### ISSUE THREAD

**Issue by Holysweet** [MaienM/ThisIsFine#1] opened 2020-05-28 12:11 UTC
Seeing the amount of mods listed looking for compat mod atm.

- [x] Advent of Ascension - all seeds
- [x] Better with Mods - Hemp seed  
- [x] Mystical Agriculture - all seeds
- [x] Pam's Harvestcraft - Amaranth seed 
- [x] Pam's Harvestcraft - Jute seed 
- [x] Pam's Harvestcraft - Giga Pickle seed
- [x] Random Things - Beans
- [x] Roots - all seeds
- [x] Rustic Thaumaturgy - Viscap Spores
- [x] Rustic Thaumaturgy - Cindermote Seeds
- [x] Forbidden & Arcanus - Golden Orchid Seed
- [x] Thaumic Additions - Vis seeds

**Comment by MaienM** [comment] 2020-06-17 16:29
Additional plants:

- [x] Rustic Thaumaturgy - Shimmerpetal Bulb
- [x] Thaumic Additions - Void Seeds

**Comment by MaienM** [comment] 2020-06-18 08:51
Some of the mods have plants that are duplicate/closely related. Here's a list of the ones I've encountered so far, and what I've done with them.

- Pam's Harvestcraft adds beans, as does Random Things
  These are merged into one (Pam's Harvestcraft's version), and planting any of them works.
- Advent of Ascension adds chili peppers, as does Pam's Harvestcraft, as does Rustic.
  These are merged into one (Pam's Harvestcraft's version), and planting any of them works. The tea sink doesn't support oredict and cannot be customized in any way, so it's disabled and recipes are added to craft the special teas with a pot.
- Advent of Ascension adds tea, as does Pam's Harvestcraft.
  These are merged into one (Pam's Harvestcraft's version), and planting any of them works.
- Actually Additions adds coffee, as does Pam's Harvestcraft.
  These are merged into one (Pam's Harvestcraft's version), and planting any of them works. The coffee machine accepts the replacement coffee beans as well.
- Pam's Harvestcraft adds grapes, as does Rustic.
  These are left as-is, since Rustic's are aesthetically interesting (I think).
- Better With Mods adds Hemp, Immersive Engineering adds Industrial Hemp.
  Both have been kept as the BWM one requires further processing, while the IE one doesn't. The BWM is flavored as a basic breed of hemp, and the IE one as a more advanced breed of hemp, hinting at this being bred to be better/easier to use.
- Forbidden & Arcanus adds Golden Orchids, Mystical Agriculture adds Gold Plants.
  This drops gold nuggets, gold ingots, and arcane gold nuggets. Because this drops arcane gold this isn't _quite_ a duplicate of Mystical Agriculture, so bot have been kept, but it's close.
- AgriCraft adds some resource crops, as goes Mystical Agriculture.
  I've opened a separate issue (#55) to discuss what to do with these.

**Comment by MaienM** [comment] 2020-06-20 10:58
The vis seeds (and the plants that grow from these) don't have a separate texture for each aspect. Instead the images that are colored based on the aspect are built up of two layers, one that is the same regardless of the aspect, and one that is recolored based on the aspect and overlaid on the first. Thaumic Additions uses a custom renderer for this, but unfortunately we cannot use this renderer when using the crops in AgriCraft.

To work around this I added a build script that takes the aforementioned textures + a list of aspects and their colors, and builds textures (and plant jsons) for all of the available varieties.

To throw an extra wrench in things there is one aspect (caeles) that does not have a static color but instead cycles through colors. This one has been special-cased and has an animated texture.

**Comment by MaienM** [comment] 2020-06-21 05:58
This one should be complete now. If any more plants are found that can't be used in agricraft we'll open a new issue for those.

**Closed as completed by MaienM** 2020-06-21 05:58 UTC
Labels: cross-mod-integration
